In [33]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/camnugent/california-housing-prices/housing.csv

In [34]:
df = pd.read_csv("/kaggle/input/datasets/camnugent/california-housing-prices/housing.csv")

In [35]:
# (1) EDA Exploratory Data Analysis
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [36]:
# row and column
df.shape

(20640, 10)

In [37]:
# OVER VIEW OF ALL DATA
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [38]:
# ye every column me kitni value null hai wo batata hai.
df.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [39]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [40]:
# step 3 missing value ko fill krna 
df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)

/tmp/ipykernel_57/102997272.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['total_bedrooms'].fillna(df['total_bedrooms'].median(), inplace=True)

In [41]:
df['total_bedrooms'].isnull().sum()

np.int64(0)

In [42]:
# ab hme jo apne data set me pridict krna hai wo nikalenge x and y ke through
y = df['median_house_value']

In [43]:
y

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [44]:
# isme jo column hm predict kr rhe us column ko drop krna baki sb ko chalaana
X = df.drop('median_house_value', axis=1)

In [45]:
X

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [46]:
# ab he encoading krni hai jis column me text value hai use categories krna aur o and 1 me todana 
x = pd.get_dummies(X, columns=['ocean_proximity'], drop_first=True)
print(x.shape)

(20640, 12)

In [47]:
# ab hm data me train and test split krenge
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test, = train_test_split(x, y, test_size=0.2, random_state=42)
print(X_train.shape)
print(X_test.shape)

(16512, 12)
(4128, 12)

In [48]:
# ab hm scaling krne ke liye start kr rhe hai.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [49]:
scaler.fit(X_train)

StandardScaler()

In [50]:
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [51]:
print(X_train_scaled)

[[ 1.27258656 -1.3728112   0.34849025 ... -0.01556621 -0.35564565
   2.62975816]
 [ 0.70916212 -0.87669601  1.61811813 ... -0.01556621 -0.35564565
   2.62975816]
 [-0.44760309 -0.46014647 -1.95271028 ... -0.01556621 -0.35564565
   2.62975816]
 ...
 [ 0.59946887 -0.75500738  0.58654547 ... -0.01556621 -0.35564565
  -0.3802631 ]
 [-1.18553953  0.90651045 -1.07984112 ... -0.01556621 -0.35564565
  -0.3802631 ]
 [-1.41489815  0.99543676  1.85617335 ... -0.01556621  2.81178749
  -0.3802631 ]]

In [52]:
# ab hm model banayenge 
from sklearn.linear_model import LinearRegression

In [53]:
model = LinearRegression()

In [54]:
model.fit(X_train_scaled, Y_train)

LinearRegression()

In [55]:
# model train ho gya hai 
# ab hm predict krenge
y_pred = model.predict(X_test_scaled)

In [56]:
y_pred

array([ 54055.44889898, 124225.33893718, 255489.37949166, ...,
       439180.98341181, 120797.55240621, 183386.04993584])

In [57]:
from sklearn.metrics import mean_squared_error, r2_score
import numpy as np

rmse = np.sqrt(mean_squared_error(Y_test, y_pred))
r2 = r2_score(Y_test, y_pred)

In [58]:
print("RMSE:", rmse)
print("R2 Score", r2)

RMSE: 70060.52184473518
R2 Score 0.6254240620553606

In [59]:
# ab hm random forest use krenge for better acccuracy model
from sklearn.ensemble import RandomForestRegressor

In [60]:
rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train_scaled, Y_train)

RandomForestRegressor(random_state=42)

In [61]:
y_pred_rf = rf_model.predict(X_test_scaled)

In [62]:
rmse_rf = np.sqrt(mean_squared_error(Y_test,y_pred_rf))
r2_rf = r2_score(Y_test, y_pred_rf)

In [63]:
print("RMS:", rmse_rf)
print("R2_score", r2_rf)

RMS: 49008.7892163409
R2_score 0.8167090228826115

** AB HM FEATURE ENGINEERING KRENGE **

In [64]:
X['rooms_per_household'] = X['total_rooms'] / X['household']
X['bedrooms_per_room'] = X['bedrooms_per_room'] / X['total_rooms']

KeyError: 'household'